Repository metno/pyaerocom, pull requests merged in 2020-05, with the labels that each got.

#115 updated ghost reader to handle new GHOST format
  pyaerocom/data/paths.ini
  pyaerocom/io/read_ghost.py
Labels: api

#111 Add class for reading EMEP model data
  .gitignore
  pyaerocom/data/emep_variables.ini
  pyaerocom/data/paths.ini
  pyaerocom/data/variables.ini
  pyaerocom/helpers.py
  pyaerocom/io/ghost_meta_keys.py
  pyaerocom/io/read_emep.py
  pyaerocom/io/read_ghost.py
  pyaerocom/io/test/test_ghost_meta_keys.py
  pyaerocom/io/test/test_read_emep.py
  pyaerocom/io/test/test_read_ghost.py
  pyaerocom/test/test_helpers.py
  pyaerocom/test/test_units_helpers.py
  pyaerocom/test/test_variable.py
  pyaerocom/units_helpers.py
  pyaerocom/variable.py
  pyaerocom/web/helpers.py
Labels: enhancement

#126 Check gridded domain
  pyaerocom/helpers.py
Labels: bug, enhancement
