Repository metno/pyaerocom, pull requests merged in 2021-12, with the labels that each got.

#511 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#524 replace deprecated np.float by no.float64
  pyaerocom/io/read_gaw.py
Labels: bug

#536 fix ungriddedata.UngriddedData.from_stationdata with single station
  pyaerocom/ungriddeddata.py
  tests/test_ungriddeddata.py
Labels: bug, good first issue

#526 Split tests with/without exceptions
  pyaerocom/_lowlevel_helpers.py
  pyaerocom/plot/heatmaps.py
  pyaerocom/utils.py
  tests/aeroval/test__processing_base.py
  tests/aeroval/test_coldatatojson_helpers2.py
  tests/aeroval/test_experiment_output.py
  tests/aeroval/test_experiment_processor.py
  tests/aeroval/test_helpers.py
  tests/aeroval/test_setupclasses.py
  tests/aeroval/test_utils.py
  tests/io/test_ebas_file_index.py
  tests/io/test_ebas_nasa_ames.py
  tests/io/test_ebas_varinfo.py
  tests/io/test_iris_io.py
  tests/io/test_read_airnow.py
  tests/io/test_read_earlinet.py
  tests/io/test_read_ebas.py
  tests/io/test_readungridded.py
  tests/io/test_readungriddedbase.py
  tests/plot/test_heatmaps.py
  tests/plot/test_mapping.py
  tests/plot/test_plotscatter.py
  tests/test__concprcp_units_helpers.py
  tests/test__init_helpers.py
  tests/test__lowlevel_helpers.py
  tests/test_aux_var_helpers.py
  tests/test_colocateddata.py
  tests/test_colocation_auto.py
  tests/test_combine_vardata_ungridded.py
  tests/test_config.py
  tests/test_griddeddata.py
  tests/test_helpers.py
  tests/test_mathutils.py
  tests/test_obs_io.py
  tests/test_stationdata.py
  tests/test_time_resampler.py
  tests/test_tstype.py
  tests/test_units_helpers.py
  tests/test_utils.py
  tests/test_varcollection.py
  tests/test_variable.py
  tests/test_vertical_profile.py
Labels: enhancement, testing

#530 use plain dicts
  pyaerocom/_concprcp_units_helpers.py
  pyaerocom/_lowlevel_helpers.py
  pyaerocom/aeroval/coldatatojson_helpers.py
  pyaerocom/aeroval/experiment_output.py
  pyaerocom/aeroval/obsentry.py
  pyaerocom/combine_vardata_ungridded.py
  pyaerocom/config.py
  pyaerocom/data/_create_var_csv_from_htap2_exceltab.py
  pyaerocom/filter.py
  pyaerocom/grid_io.py
  pyaerocom/griddeddata.py
  pyaerocom/io/aerocom_browser.py
  pyaerocom/io/ebas_nasa_ames.py
  pyaerocom/io/ebas_varinfo.py
  pyaerocom/io/fileconventions.py
  pyaerocom/io/helpers.py
  pyaerocom/io/read_aasetal.py
  pyaerocom/io/read_aeolus_l2a_data.py
  pyaerocom/io/read_aeronet_invv2.py
  pyaerocom/io/read_aeronet_invv3.py
  pyaerocom/io/read_aeronet_sdav2.py
  pyaerocom/io/read_aeronet_sdav3.py
  pyaerocom/io/read_aeronet_sunv2.py
  pyaerocom/io/read_aeronet_sunv3.py
  pyaerocom/io/read_airnow.py
  pyaerocom/io/read_earlinet.py
  pyaerocom/io/read_ebas.py
  pyaerocom/io/read_eea_aqerep_base.py
  pyaerocom/io/read_gaw.py
  pyaerocom/io/read_marcopolo.py
  pyaerocom/io/read_mscw_ctm.py
  pyaerocom/io/read_sentinel5p_data.py
  pyaerocom/io/readaeronetbase.py
  pyaerocom/io/readgridded.py
  pyaerocom/io/readsatellitel2base.py
  pyaerocom/io/readungriddedbase.py
  pyaerocom/metastandards.py
  pyaerocom/stationdata.py
  pyaerocom/trends_engine.py
  pyaerocom/trends_helpers.py
  pyaerocom/ungriddeddata.py
  pyaerocom/varcollection.py
  pyaerocom/variable.py
  tests/aeroval/test_glob_defaults.py
  tests/io/test_dms_gaw.py
  tests/io/test_ebas_nasa_ames.py
  tests/io/test_readgridded.py
  tests/test_metastandards.py
Labels: enhancement, style

#531 use importlib.resources/metadata instead of pyaeorocom.__dir__/__version__
  pyaerocom/__init__.py
  pyaerocom/_logging.py
  pyaerocom/config.py
  pyaerocom/io/ebas_varinfo.py
  pyaerocom/io/fileconventions.py
  pyaerocom/io/helpers.py
  pyaerocom/metastandards.py
  pyaerocom/variable_helpers.py
  setup.cfg
  tests/conftest.py
  tests/test__logging.py
  tests/test_config.py
  tests/test_varcollection.py
Labels: enhancement, style
