Repository metno/pyaerocom, pull requests merged in 2021-02, with the labels that each got.

#307 Add reading routine for AirNow obs dataset
  pyaerocom/config.py
  pyaerocom/data/paths.ini
  pyaerocom/io/__init__.py
  pyaerocom/io/aux_read_cubes.py
  pyaerocom/io/read_airnow.py
  pyaerocom/io/readungridded.py
  pyaerocom/io/test/test_read_airnow.py
  pyaerocom/molmasses.py
  pyaerocom/testdata_access.py
Labels: enhancement, new-obs

#309 Griesie eea dev
  pyaerocom/config.py
  pyaerocom/io/country_codes.json
  pyaerocom/io/helpers.py
  pyaerocom/io/read_eea_aqerep.py
  pyaerocom/io/readungridded.py
Labels: enhancement, new-obs

#295 Updates in processing of trends analysis
  pyaerocom/web/trends_evaluation.py
Labels: api, enhancement

#315 Updates needed to combine several observations into one superobservation
  pyaerocom/colocateddata.py
  pyaerocom/colocation.py
  pyaerocom/io/helpers_units.py
  pyaerocom/io/read_airnow.py
  pyaerocom/io/read_eea_aqerep_base.py
  pyaerocom/io/read_marcopolo.py
  pyaerocom/io/test/test_read_airnow.py
  pyaerocom/test/test_colocation_auto.py
  pyaerocom/ungriddeddata.py
  pyaerocom/web/aerocom_evaluation.py
  pyaerocom/web/helpers.py
  pyaerocom/web/helpers_evaluation_iface.py
  pyaerocom/web/test/test_helpers.py
Labels: api, enhancement

#260 Updates for new model maps evaluation interface
  pyaerocom/colocateddata.py
  pyaerocom/colocation_auto.py
  pyaerocom/data/variables.ini
  pyaerocom/griddeddata.py
  pyaerocom/io/ebas_nasa_ames.py
  pyaerocom/io/iris_io.py
  pyaerocom/io/read_ebas.py
  pyaerocom/io/readgridded.py
  pyaerocom/test/test_tstype.py
  pyaerocom/time_config.py
  pyaerocom/time_resampler.py
  pyaerocom/tstype.py
  pyaerocom/units_helpers.py
  pyaerocom/variable.py
  pyaerocom/web/aerocom_evaluation.py
  pyaerocom/web/cli/main_aerocom_evaluation.py
  pyaerocom/web/helpers_evaluation_iface.py
  pyaerocom/web/trends_evaluation.py
  pyaerocom/web/utils.py
  pyaerocom/web/web_maps_helpers.py
  pyaerocom/web/web_naming_conventions.py
Labels: enhancement

#269 Evaluation of concentration in precipitation and wet deposition
  changelog/v0110_release_summary.md
  pyaerocom/__init__.py
  pyaerocom/colocation.py
  pyaerocom/data/ebas_config.ini
  pyaerocom/data/paths.ini
  pyaerocom/data/variables.ini
  pyaerocom/griddeddata.py
  pyaerocom/helpers.py
  pyaerocom/io/__init__.py
  pyaerocom/io/aux_read_cubes.py
  pyaerocom/io/ebas_varinfo.py
  pyaerocom/io/read_ebas.py
  pyaerocom/io/read_ghost.py
  pyaerocom/io/read_mscw_ctm.py
  pyaerocom/io/readgridded.py
  pyaerocom/io/test/test_ebas_varinfo.py
  pyaerocom/io/test/test_read_ebas.py
  pyaerocom/io/test/test_readgridded.py
  pyaerocom/mathutils.py
  pyaerocom/molmasses.py
  pyaerocom/plot/plotscatter.py
  pyaerocom/test/test_custom_unit_conversion.py
  pyaerocom/test/test_molmasses.py
  pyaerocom/test/test_time_resampler.py
  pyaerocom/test/test_tstype.py
  pyaerocom/test/test_variable.py
  pyaerocom/time_config.py
  pyaerocom/time_resampler.py
  pyaerocom/tstype.py
  pyaerocom/units_helpers.py
  pyaerocom/var_groups.py
  pyaerocom/variable.py
  pyaerocom/web/aerocom_evaluation.py
  pyaerocom/web/helpers_evaluation_iface.py
  pyaerocom/web/web_naming_conventions.py
Labels: api, enhancement

#297 Revise logic related to outlier removal in low and high level colocation routines
  pyaerocom/colocation.py
  pyaerocom/colocation_auto.py
  pyaerocom/test/test_colocation.py
  pyaerocom/test/test_colocation_auto.py
Labels: api, enhancement, missing-tests

#310 New obsdata reading routines for CAMS84 project
  pyaerocom/__init__.py
  pyaerocom/_lowlevel_helpers.py
  pyaerocom/colocateddata.py
  pyaerocom/colocation.py
  pyaerocom/config.py
  pyaerocom/data/paths.ini
  pyaerocom/data/regions.ini
  pyaerocom/data/variables.ini
  pyaerocom/filter.py
  pyaerocom/helpers_landsea_masks.py
  pyaerocom/io/__init__.py
  pyaerocom/io/country_codes.json
  pyaerocom/io/helpers.py
  pyaerocom/io/helpers_units.py
  pyaerocom/io/read_airnow.py
  pyaerocom/io/read_eea_aqerep.py
  pyaerocom/io/read_eea_aqerep_base.py
  pyaerocom/io/read_eea_aqerep_v2.py
  pyaerocom/io/read_ghost.py
  pyaerocom/io/read_marcopolo.py
  pyaerocom/io/readungridded.py
  pyaerocom/io/test/test_read_airnow.py
  pyaerocom/mathutils.py
  pyaerocom/obs_io.py
  pyaerocom/region.py
  pyaerocom/region_defs.py
  pyaerocom/test/test_colocateddata.py
  pyaerocom/test/test_colocation_auto.py
  pyaerocom/test/test_filter.py
  pyaerocom/testdata_access.py
  pyaerocom/tstype.py
  pyaerocom/ungriddeddata.py
  pyaerocom/variable.py
  pyaerocom/web/aerocom_evaluation.py
  pyaerocom/web/helpers.py
  pyaerocom/web/helpers_evaluation_iface.py
  pyaerocom/web/test/test_helpers.py
  pyaerocom/web/trends_evaluation.py
Labels: enhancement, new-obs
