Repository metno/pyaerocom, pull requests merged in 2021-09, with the labels that each got.

#389 Harmonisation of ungridded reading API
  pyaerocom/colocation_auto.py
  pyaerocom/combine_vardata_ungridded.py
  pyaerocom/config.py
  pyaerocom/io/cachehandler_ungridded.py
  pyaerocom/io/helpers.py
  pyaerocom/io/iris_io.py
  pyaerocom/io/read_aeolus_l2a_data.py
  pyaerocom/io/read_aeronet_invv2.py
  pyaerocom/io/read_aeronet_invv3.py
  pyaerocom/io/read_aeronet_sdav2.py
  pyaerocom/io/read_aeronet_sunv2.py
  pyaerocom/io/read_airnow.py
  pyaerocom/io/read_earlinet.py
  pyaerocom/io/read_ebas.py
  pyaerocom/io/read_eea_aqerep_base.py
  pyaerocom/io/read_ghost.py
  pyaerocom/io/read_marcopolo.py
  pyaerocom/io/read_sentinel5p_data.py
  pyaerocom/io/readaeronetbase.py
  pyaerocom/io/readsatellitel2base.py
  pyaerocom/io/readungridded.py
  pyaerocom/io/readungriddedbase.py
  pyaerocom/io/test/test_read_aasetal.py
  pyaerocom/io/test/test_read_airnow.py
  pyaerocom/io/test/test_read_ghost.py
  pyaerocom/io/test/test_readungridded.py
  pyaerocom/io/test/test_readungriddedbase.py
  pyaerocom/test/test_utils.py
  pyaerocom/ungriddeddata.py
  pyaerocom/utils.py
  pyaerocom/web/aerocom_evaluation.py
  pyaerocom/web/helpers_evaluation_iface.py
Labels: enhancement, api, style, user-friendliness

#416 Improve flexibility for computation of statistics timeseries in AeroVal
  pyaerocom/aeroval/coldatatojson_engine.py
  pyaerocom/aeroval/setupclasses.py
  pyaerocom/aeroval/test/test_coldatatojson_engine.py
  pyaerocom/colocateddata.py
  pyaerocom/exceptions.py
  pyaerocom/helpers.py
  pyaerocom/time_config.py
Labels: enhancement

#354 Implement support for evaluation of model climatology files #341
  docs/api.rst
  pyaerocom/colocation.py
  pyaerocom/colocation_auto.py
  pyaerocom/config.py
  pyaerocom/exceptions.py
  pyaerocom/helpers.py
  pyaerocom/io/helpers.py
  pyaerocom/io/iris_io.py
  pyaerocom/io/readgridded.py
  pyaerocom/io/test/test_iris_io.py
  pyaerocom/testdata_access.py
  tests/io/test_readgridded.py
  tests/test_colocation.py
  tests/test_colocation_auto.py
  tests/test_griddeddata.py
Labels: new-feature

#419 Add documentation
  pyaerocom/colocation.py
Labels: documentation

#422 Increase flexibility of ColocationSetup attributes
  pyaerocom/__init__.py
  pyaerocom/aeroval/modelmaps_helpers.py
  pyaerocom/colocation_auto.py
  tests/test__lowlevel_helpers.py
  tests/test_colocation_auto.py
Labels: bug-dev-branch

#428 More cleanup, docs and tests
  pyaerocom/_init_helpers.py
  pyaerocom/plot/_sorted_out/plot_map_OLD.py
  pyaerocom/plot/mapping.py
  pyaerocom/test/README.md
  pyaerocom/tools/__init__.py
  setup.py
  tests/README.md
  tests/aeroval/test_coldatatojson_engine.py
  tests/io/test_iris_io.py
  tests/test__init_helpers.py
Labels: testing, documentation

#434 Move method _get_diurnal_only from ExperimentProcessor to HasColocator
  pyaerocom/aeroval/_processing_base.py
  pyaerocom/aeroval/experiment_processor.py
Labels: aeroval-tools

#426 Add trends
  pyaerocom/aeroval/coldatatojson_engine.py
  pyaerocom/aeroval/glob_defaults.py
  pyaerocom/aeroval/setupclasses.py
  pyaerocom/exceptions.py
  pyaerocom/trends_helpers.py
  tests/_conftest_helpers.py
  tests/aeroval/test_coldatatojson_engine.py
  tests/conftest.py
Labels: aeroval-tools

#446 Add codecov badge in README
  README.rst
Labels: testing, documentation

#439 Fix 438 (among other small bugs related to AeroVal tools)
  pyaerocom/_lowlevel_helpers.py
  pyaerocom/aeroval/_lowlev.py
  pyaerocom/aeroval/collections.py
  pyaerocom/aeroval/experiment_output.py
  pyaerocom/aeroval/modelentry.py
  pyaerocom/aeroval/modelmaps_engine.py
  pyaerocom/aeroval/modelmaps_helpers.py
  pyaerocom/aeroval/obsentry.py
  pyaerocom/aeroval/setupclasses.py
  pyaerocom/colocateddata.py
  pyaerocom/colocation.py
  pyaerocom/colocation_auto.py
  pyaerocom/griddeddata.py
  pyaerocom/io/read_mscw_ctm.py
  pyaerocom/io/readgridded.py
  pyaerocom/io/readungridded.py
  pyaerocom/mathutils.py
  pyaerocom/variable.py
  pyaerocom/vert_coords.py
  pyaerocom_env.yml
  setup.py
  tests/aeroval/test_experiment_output.py
  tests/aeroval/test_modelmaps_helpers.py
  tests/io/test_read_ebas.py
  tests/io/test_read_mscw_ctm.py
  tests/io/test_readgridded.py
  tests/test_colocation_auto.py
  tests/test_griddeddata.py
  tests/test_mathutils.py
Labels: aeroval-tools
