Repository metno/pyaerocom, pull requests merged in 2022-03, with the labels that each got.

#598 Docs551
  docs/api.rst
  pyaerocom/io/read_marcopolo.py
Labels: documentation

#607 Fairmode Beta*MQI
  pyaerocom/aeroval/coldatatojson_helpers.py
  pyaerocom/aeroval/fairmode_stats.py
  tests/aeroval/test_compute_fairmode_stats.py
Labels: new-feature, aeroval-tools

#613 add Fairmode statistic to aeroval output
  pyaerocom/aeroval/coldatatojson_engine.py
  pyaerocom/aeroval/coldatatojson_helpers.py
  pyaerocom/aeroval/fairmode_stats.py
  pyaerocom/aeroval/setupclasses.py
  tests/aeroval/test_compute_fairmode_stats.py
Labels: new-feature
