Repository metno/pyaerocom, pull requests merged in 2022-11, with the labels that each got.

#761 obs_only_stats flag in config
  pyaerocom/aeroval/experiment_output.py
  pyaerocom/aeroval/glob_defaults.py
  pyaerocom/aeroval/setupclasses.py
Labels: enhancement, aeroval-tools

#783 conda-forge compatibility
  .github/workflows/CI.yml
  pyaerocom/_logging.py
  pyaerocom/config.py
  pyaerocom/data/resources.py
  pyaerocom/io/ebas_varinfo.py
  pyaerocom/io/fileconventions.py
  pyaerocom/io/helpers.py
  pyaerocom/metastandards.py
  pyaerocom/plugins/ghost/meta_keys.py
  pyaerocom/plugins/mscw_ctm/model_variables.py
  pyaerocom/variable_helpers.py
  pyaerocom_env.yml
  pyproject.toml
  tests/test_config.py
  tests/test_varcollection.py
Labels: dependencies

#796 run CI for Python 3.11 on Ubuntu 22.04
  .github/workflows/CI.yml
  pyproject.toml
Labels: testing
