Repository metno/pyaerocom, pull requests merged in 2023-10, with the labels that each got.

#855 Upgrade Earlinet reader and implement vertical profiles
  pyaerocom/aeroval/coldatatojson_engine.py
  pyaerocom/aeroval/coldatatojson_helpers.py
  pyaerocom/aeroval/fairmode_stats.py
  pyaerocom/aeroval/modelentry.py
  pyaerocom/aeroval/obsentry.py
  pyaerocom/aeroval/setupclasses.py
  pyaerocom/colocateddata.py
  pyaerocom/colocation.py
  pyaerocom/colocation_3d.py
  pyaerocom/colocation_auto.py
  pyaerocom/data/paths.ini
  pyaerocom/data/variables.ini
  pyaerocom/extras/satellite_l2/aeolus_l2a.py
  pyaerocom/griddeddata.py
  pyaerocom/io/fileconventions.py
  pyaerocom/io/iris_io.py
  pyaerocom/io/read_earlinet.py
  pyaerocom/io/readungridded.py
  pyaerocom/stationdata.py
  pyaerocom/ungriddeddata.py
  pyaerocom/vert_coords.py
  pyaerocom/vertical_profile.py
  pyaerocom_env.yml
  tests/aeroval/test_aeroval_HIGHLEV.py
  tests/aeroval/test_coldatatojson_helpers2.py
  tests/aeroval/test_experiment_output.py
  tests/fixtures/data_access.py
  tests/io/test_read_earlinet.py
  tests/test_colocation_3d.py
  tests/test_helpers.py
  tests/test_stationdata.py
Labels: obs-update, CAMS2_82

#921 Fix plugins for ICOS and mmr vs vmr issue
  pyaerocom/aeroval/glob_defaults.py
  pyaerocom/data/variables.ini
  pyaerocom/molmasses.py
  pyproject.toml
  tests/plugins/test_entry_points.py
Labels: CAMS2_82

#928 Update Dependencies
  .github/workflows/CI.yml
  pyaerocom_env.yml
  pyproject.toml
Labels: testing, dependencies
