Repository metno/pyaerocom, pull requests merged in 2024-12, with the labels that each got.

#1446 Bug fix: infer info from geojson files in contour dir as well
  pyaerocom/aeroval/experiment_output.py
Labels: bug :bug:

#1456 Reduce test warnings
  pyaerocom/io/ebas_nasa_ames.py
  pyaerocom/io/read_earlinet.py
  pyaerocom/stats/mda8/mda8.py
Labels: testing

#1418 variables_changed_units_categories
  pyaerocom/aeroval/glob_defaults.py
  pyaerocom/data/variables.ini
Labels: good first issue

#1445 Add post-processing of observations from pyaro
  pyaerocom/config.py
  pyaerocom/io/pyaro/postprocess.py
  pyaerocom/io/pyaro/pyaro_config.py
  pyaerocom/io/pyaro/read_pyaro.py
  pyaerocom/io/readungridded.py
  tests/fixtures/pyaro.py
  tests/io/pyaro/test_read_pyaro.py
Labels: aerotools convo 💬
