Repository metno/pyaerocom, pull requests merged in 2024-03, with the labels that each got.

#1032 run CI tests only on PRs
  .github/workflows/CI.yml
Labels: testing

#1033 update GH action version
  .github/workflows/close_issues.yml
Labels: automation

#1035 drop Python 3.9 support
  .github/workflows/CI.yml
  .readthedocs.yaml
  pyaerocom/colocation_auto.py
  pyaerocom/io/readungridded.py
  pyaerocom_env.yml
  pyproject.toml
  tests/plugins/test_entry_points.py
Labels: testing, user-friendliness

#1048 Fix "vertical" typo
  pyaerocom/colocation_auto.py
Labels: bug

#1055 Introduce a PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: automation

#1040 Update GH actions
  .github/workflows/CI.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: testing, automation

#1064 Better default ranges for bsc532aer and ec532aer visualization on Aeroval
  pyaerocom/aeroval/glob_defaults.py
Labels: aeroval-tools

#1062 add Python 3.12 support
  .github/workflows/CI.yml
  pyaerocom/aeroval/coldatatojson_helpers.py
  pyproject.toml
Labels: enhancement

#1069 Change the name of the statistic Mean Bias to MB on Aeroval
  pyaerocom/aeroval/glob_defaults.py
Labels: aeroval-tools

#1070 warnings are not test errors
  pyaerocom/__init__.py
  pyaerocom/_warnings.py
  pyproject.toml
  tests/io/mscw_ctm/test_reader.py
Labels: enhancement, testing

#1075 Json write speedup by avoiding multiple float-conversions
  pyaerocom/_lowlevel_helpers.py
  pyaerocom/aeroval/coldatatojson_helpers.py
  pyaerocom/aeroval/json_utils.py
Labels: enhancement, CAMS2_83

#1072 Fix typos and clean up docstrings in CLI
  pyaerocom/scripts/cli.py
Labels: user-friendliness

#1079 Fix pip cache on CI
  .github/workflows/CI.yml
  pyaerocom/io/readungridded.py
Labels: testing
