Repository metno/pyaerocom, pull requests merged in 2024-05, with the labels that each got.

#1145 Use logger.info rather than logging.info to get correct class
  pyaerocom/aeroval/experiment_processor.py
  pyaerocom/extras/satellite_l2/aeolus_l2a.py
  pyaerocom/extras/satellite_l2/base_reader.py
  pyaerocom/extras/satellite_l2/sentinel5p.py
  pyaerocom/io/cams2_83/read_obs.py
Labels: user-friendliness

#1151 Upgrade pandas
  pyaerocom_env.yml
  pyproject.toml
Labels: dependencies

#1102 Adds possibility of muliple ts per station
  pyaerocom/io/pyaro/read_pyaro.py
  tests/fixtures/pyaro.py
  tests/io/pyaro/test_read_pyaro.py
Labels: enhancement

#1124 Readpyaro extension
  pyaerocom/io/pyaro/read_pyaro.py
  pyaerocom_env.yml
  pyproject.toml
  tests/fixtures/pyaro.py
  tests/io/pyaro/test_read_pyaro.py
Labels: enhancement

#1147 Custom variables when running aeroval
  pyaerocom/aeroval/experiment_processor.py
  pyaerocom/aeroval/modelentry.py
  pyaerocom/colocation_auto.py
  pyaerocom/config.py
  pyaerocom/data/emep_variables.ini
  pyaerocom/data/variables.ini
  pyaerocom/io/mscw_ctm/additional_variables.py
  pyaerocom/io/mscw_ctm/emep_variables.toml
  pyaerocom/io/mscw_ctm/reader.py
  pyaerocom/io/pyaro/read_pyaro.py
  tests/fixtures/pyaro.py
  tests/io/mscw_ctm/test_reader.py
  tests/test_config.py
  tests/test_varcollection.py
Labels: enhancement

#1116 Adds pollen variables needed by gunnar
  pyaerocom/data/emep_variables.ini
  pyaerocom/data/variables.ini
  pyaerocom/io/mscw_ctm/additional_variables.py
  pyaerocom/io/mscw_ctm/emep_variables.toml
  pyaerocom/io/mscw_ctm/reader.py
Labels: enhancement
