Repository metno/pyaerocom, pull requests merged in 2024-06, with the labels that each got.

#1120 Pydantic ColocationSetup
  pyaerocom/aeroval/_processing_base.py
  pyaerocom/aeroval/experiment_processor.py
  pyaerocom/aeroval/helpers.py
  pyaerocom/aeroval/setupclasses.py
  pyaerocom/colocation_auto.py
  pyaerocom/colocation_setup.py
  pyaerocom/helpers.py
  pyaerocom/scripts/cams2_83/processer.py
  tests/aeroval/test__processing_base.py
  tests/aeroval/test_setupclasses.py
  tests/fixtures/aeroval/cfg_test_exp1.py
  tests/fixtures/aeroval/cfg_test_exp2.py
  tests/fixtures/aeroval/cfg_test_exp3.py
  tests/fixtures/aeroval/cfg_test_exp4.py
  tests/fixtures/aeroval/cfg_test_exp5.py
  tests/fixtures/mscw_ctm.py
  tests/fixtures/pyaro.py
  tests/io/pyaro/test_read_pyaro.py
  tests/test_colocation_auto.py
  tests/test_colocation_setup.py
Labels: CAMS2_82

#1179 Earlinet v3
  pyaerocom/data/paths.ini
  pyaerocom/data/variables.ini
Labels: obs-update

#1187 setting default contour-map extend max
  pyaerocom/aeroval/modelmaps_helpers.py
Labels: CAMS2_83

#1184 Changes colocation setup to use only model kwargs. Adds validator, with test
  pyaerocom/colocation_auto.py
  pyaerocom/colocation_setup.py
  tests/test_colocation_setup.py
Labels: bug

#1198 Adds missing f to f string for printing info about variable
  pyaerocom/variable.py
Labels: bug

#1207 numpy <2.0.0
  pyaerocom_env.yml
  pyproject.toml
Labels: bug, dependencies

#1219 update ubservations name for the web for CAMS2_83
  pyaerocom/scripts/cams2_83/config.py
  tests/cams2_83/test_cams2_83_cli_mos.py
  tests/fixtures/cams2_83/config.py
Labels: CAMS2_83

#1220 Fixes for map-plotting of emep-results
  pyaerocom/aeroval/glob_defaults.py
  pyaerocom/aeroval/helpers.py
  pyaerocom/aeroval/modelmaps_engine.py
  pyaerocom/aeroval/varinfo_web.py
  pyaerocom/colocation/colocation_setup.py
  pyaerocom/data/variables.ini
  pyaerocom/griddeddata.py
Labels: aeroval-tools

#1230 put all temporary and testing data below the path ~/MyPyaerocom
  pyaerocom/config.py
Labels: testing
