Repository metno/pyaerocom, pull requests merged in 2024-02, with the labels that each got.

#974 fix pytest 8 warnings
  tests/plugins/gaw/test_dms.py
  tests/plugins/icos/test_reader.py
  tests/plugins/ipcforests/test_reader.py
  tests/plugins/mep/test_reader.py
Labels: testing, dependencies

#979 Fix up ICOS reader and tests to work with CO2, CH3, and CO
  pyaerocom/plugins/icos/reader.py
  tests/plugins/icos/test_reader.py
Labels: testing

#973 Fix bugs in 3d collocation and profile processing
  pyaerocom/aeroval/coldatatojson_engine.py
  pyaerocom/colocation_3d.py
  pyaerocom/data/variables.ini
  pyaerocom/plugins/ipcforests/metadata.py
Labels: bug, CAMS2_82

#997 missing temporary path to unpack testdata-minimal.tar.gz
  pyproject.toml
  tests/fixtures/data_access.py
Labels: testing

#993 Make computed statistics configurable by allowing dropping of default statistics and specification of the number of decimals shown
  pyaerocom/aeroval/coldatatojson_engine.py
  pyaerocom/aeroval/coldatatojson_helpers.py
  pyaerocom/aeroval/experiment_output.py
  pyaerocom/aeroval/setupclasses.py
  pyaerocom/mathutils.py
  tests/aeroval/test_coldatatojson_helpers2.py
  tests/aeroval/test_experiment_output.py
Labels: enhancement, CAMS2_83, CAMS2_82

#998 run AeroVal experiment from CLI
  pyaerocom/scripts/cli.py
  tests/fixtures/data_access.py
  tests/test_cli.py
Labels: enhancement, user-friendliness

#1014 Cleanup using autoflake
  pyaerocom/aeroval/experiment_processor.py
  pyaerocom/aeroval/helpers.py
  pyaerocom/extras/satellite_l2/aeolus_l2a.py
  pyaerocom/extras/satellite_l2/base_reader.py
  pyaerocom/extras/satellite_l2/sentinel5p.py
  pyaerocom/helpers.py
  pyaerocom/io/aux_components_fun.py
  pyaerocom/io/read_earlinet.py
  pyaerocom/plugins/icos/reader.py
  pyaerocom/varcollection.py
  tests/aeroval/test_utils.py
  tests/io/test_ebas_file_index.py
Labels: style
