Repository metno/pyaerocom, pull requests merged in 2024-10, with the labels that each got.

#1355 Fix metaindx shift after metadata filter
  pyaerocom/ungriddeddata.py
Labels: bug :bug:

#1357 Fix set equivalence checking in ModelMapsEngine
  pyaerocom/aeroval/modelmaps_engine.py
Labels: bug :bug:

#1360 Pydantic ObsEntry
  pyaerocom/aeroval/_processing_base.py
  pyaerocom/aeroval/collections.py
  pyaerocom/aeroval/experiment_output.py
  pyaerocom/aeroval/experiment_processor.py
  pyaerocom/aeroval/helpers.py
  pyaerocom/aeroval/obsentry.py
  pyaerocom/aeroval/setup_classes.py
  pyaerocom/aeroval/superobs_engine.py
  pyaerocom/colocation/colocation_setup.py
  pyaerocom/io/__init__.py
  pyaerocom/io/file_conventions.py
  pyaerocom/io/helpers.py
  pyaerocom/io/iris_io.py
  pyaerocom/io/readgridded.py
  tests/aeroval/test__processing_base.py
  tests/aeroval/test_collections.py
  tests/aeroval/test_setup_classes.py
Labels: code-health 🏥

#1365 Clarify requirements for sample_points in interpolate()
  pyaerocom/griddeddata.py
Labels: documentation
