Repository metno/pyaerocom, pull requests merged in 2024-04, with the labels that each got.

#1017 Pydantic for Aeroval setupclasses.py
  pyaerocom/_lowlevel_helpers.py
  pyaerocom/aeroval/experiment_output.py
  pyaerocom/aeroval/json_utils.py
  pyaerocom/aeroval/setupclasses.py
  pyaerocom_env.yml
  pyproject.toml
  tests/aeroval/test__processing_base.py
  tests/aeroval/test_aeroval_HIGHLEV.py
  tests/aeroval/test_experiment_output.py
  tests/aeroval/test_setup.py
  tests/io/mep/test_reader.py
Labels: style, user-friendliness

#1088 Fix Pydantic namespace conflict in StatisticSetup
  pyaerocom/aeroval/setupclasses.py
Labels: style, low-hanging-fruit-🍎

#1092 Temporary fix for test_etopo_altitude
  pyproject.toml
Labels: testing

#1093 Use cached_property decorator on setupclasses.py::EvalSetup attributes which are computed_fields
  pyaerocom/aeroval/setupclasses.py
Labels: CAMS2_83

#1110 Implement tests for EvalSetup component classes.
  pyaerocom/aeroval/setupclasses.py
  tests/aeroval/test_setupclasses.py
Labels: testing

#1128 Merge CAMS2-83 code to main-dev
  hoqq
  pyaerocom/aeroval/coldatatojson_engine.py
  pyaerocom/aeroval/coldatatojson_helpers.py
  pyaerocom/aeroval/helpers.py
  pyaerocom/aeroval/setupclasses.py
  pyaerocom/colocation_auto.py
  pyaerocom/config.py
  pyaerocom/griddeddata.py
  pyaerocom/io/__init__.py
  pyaerocom/io/cams2_83/__init__.py
  pyaerocom/io/cams2_83/models.py
  pyaerocom/io/cams2_83/obs.py
  pyaerocom/io/cams2_83/read_obs.py
  pyaerocom/io/cams2_83/reader.py
  pyaerocom/io/readungridded.py
  pyaerocom/scripts/cams2_83/__init__.py
  pyaerocom/scripts/cams2_83/cli.py
  pyaerocom/scripts/cams2_83/config.py
  pyaerocom/scripts/cams2_83/engine.py
  pyaerocom/scripts/cams2_83/evaluation.py
  pyaerocom/scripts/cams2_83/processer.py
  pyaerocom/stationdata.py
  pyaerocom/time_resampler.py
  pyaerocom/ungriddeddata.py
  pyaerocom_env.yml
  pyproject.toml
  tests/aeroval/test_helpers.py
  tests/cams2_83/test_cams2_83_cli.py
  tests/cams2_83/test_cams2_83_evaluation.py
  tests/conftest.py
  tests/fixtures/aeroval/common.py
  tests/fixtures/cams2_83/cfg_test.py
  tests/fixtures/cams2_83/config.py
  tests/io/cams2_83/__init__.py
  tests/io/cams2_83/test_models.py
  tests/io/cams2_83/test_read_obs.py
  tests/io/cams2_83/test_reader.py
Labels: CAMS2_83

#1060 Read colocated files made outside of pyaerocom
  pyaerocom/aeroval/experiment_processor.py
  pyaerocom/aeroval/obsentry.py
Labels: enhancement, CAMS2_82
