Repository metno/pyaerocom, pull requests merged in 2024-09, with the labels that each got.

#1335 Adds better definition of filters. Adds tqdm to read_pyaro
  pyaerocom/io/pyaro/pyaro_config.py
  pyaerocom/io/pyaro/read_pyaro.py
Labels: bug :bug:

#1322 Fix mda8 misalignment
  pyaerocom/stats/mda8/mda8.py
  tests/stats/mda8/test_mda8.py
Labels: bug :bug:

#1318 Add link to directive to mda8 documentation
  pyaerocom/stats/mda8/mda8.py
Labels: documentation

#1320 Adds more detailed descriptions to the mda8 variables.
  pyaerocom/data/variables.ini
Labels: documentation

#1351 Bump aerovaldb / Support put_map_overlay() in pyaerocom
  pyaerocom/aeroval/experiment_output.py
  pyaerocom_env.yml
  pyproject.toml
Labels: dependencies
