Repository metno/pyaerocom, pull requests merged in 2024-11, with the labels that each got.

#1400 allow list of strings and Path like objects in PyaroConfig
  pyaerocom/io/pyaro/pyaro_config.py
Labels: enhancement ✨

#1402 add pya init command
  docs/install.rst
  pyaerocom/scripts/cli.py
  tests/test_cli.py
Labels: user-friendliness

#1405 Fix reference to OBS_VERT_TYPES_ALT
  pyaerocom/colocation/colocator.py
Labels: bug :bug:

#1407 Make Aeroval Collections Composite patterns
  pyaerocom/aeroval/collections.py
  pyaerocom/aeroval/experiment_output.py
  pyaerocom/aeroval/helpers.py
  pyaerocom/aeroval/setup_classes.py
  pyaerocom/aeroval/superobs_engine.py
  pyaerocom/aeroval/utils.py
  tests/aeroval/test_aeroval_HIGHLEV.py
  tests/aeroval/test_collections.py
  tests/aeroval/test_experiment_output.py
  tests/aeroval/test_experiment_processor.py
  tests/aeroval/test_helpers.py
Labels: code-health 🏥

#1410 Lowlevel helpers clean up
  pyaerocom/_lowlevel_helpers.py
  pyaerocom/aeroval/aux_io_helpers.py
  tests/aeroval/test_aux_io_helpers.py
Labels: code-health 🏥

#1416 New minimaldata
  pyaerocom/sample_data_access/minimal_dataset.py
Labels: bug :bug:

#1406 Some work for reading ColocatedData provided by CAMS2_82 partners
  pyaerocom/aeroval/coldatatojson_engine.py
  pyaerocom/aeroval/collections.py
  pyaerocom/aeroval/setup_classes.py
Labels: CAMS2_82

#1424 Fix call to model_cfg to use getter function
  pyaerocom/aeroval/modelmaps_engine.py
Labels: bug :bug:

#1427 Obs name big fix
  pyaerocom/aeroval/collections.py
  pyaerocom/aeroval/obsentry.py
  tests/aeroval/test_experiment_output.py
Labels: bug :bug:

#1431 Pixel maps debug
  pyaerocom/aeroval/setup_classes.py
Labels: bug :bug:, CAMS2_82, SESAM
