Repository metno/pyaerocom, pull requests merged in 2024-07, with the labels that each got.

#1278 Fix 70% of rounding performance issue
  pyaerocom/aeroval/coldatatojson_helpers.py
  pyaerocom/stats/stats.py
Labels: performance

#1280 add missing definitions for conco3mda8, necessary for cams2_83
  pyaerocom/aeroval/data/var_scale_colmap.ini
  pyaerocom/aeroval/data/var_web_info.ini
  pyaerocom/data/variables.ini
  pyaerocom/scripts/cams2_83/config.py
  pyaerocom/stats/mda8/const.py
  tests/test_varcollection.py
Labels: CAMS2_83

#1281 docs: Fix missing download testdata section in documentation
  docs/api.rst
  pyaerocom/sample_data_access/minimal_dataset.py
Labels: documentation

#1284 Fix mda8 crash when configured frequencies are all hourly
  pyaerocom/colocation/colocation_setup.py
  pyaerocom/colocation/colocator.py
Labels: bug

#1285 Fix printing all writes to stdout
  pyaerocom_env.yml
  pyproject.toml
Labels: bug
