Repository metno/pyaerocom, pull requests merged in 2025-04, with the labels that each got.

#1530 1526 create example configuration using the actrisebas pyaro reader
  pyaerocom/aeroval/config/emep/reporting_base.py
  pyaerocom/aeroval/config/pyaro/base_config.py
  pyaerocom/aeroval/config/pyaro/omit_stations_actris_ebas.yaml
  pyaerocom/aeroval/experiment_output.py
  pyaerocom/aeroval/superobs_engine.py
  pyaerocom/colocation/colocated_data.py
  pyaerocom/colocation/colocation_utils.py
  pyaerocom/colocation/uemep/colocator.py
  pyaerocom/griddeddata.py
  pyaerocom/io/ebas_nasa_ames.py
  pyaerocom/io/ebas_varinfo.py
  pyaerocom/io/helpers.py
  pyaerocom/io/read_eea_aqerep_base.py
  pyaerocom/io/readaeronetbase.py
  pyaerocom/io/readgridded.py
  pyaerocom/stationdata.py
  pyaerocom/ungridded_data_metadata.py
  pyaerocom/ungriddeddata.py
  pyaerocom/variable.py
Labels: new-obs

#1589 mmrco + mmrch4 in variables.ini
  pyaerocom/data/variables.ini
Labels: CAMS2_82

#1601 Change all occurrences of self.logger to logger
  pyaerocom/_lowlevel_helpers.py
  pyaerocom/colocation/colocator.py
  pyaerocom/io/gaw/reader.py
  pyaerocom/io/read_aeronet_invv3.py
  pyaerocom/io/read_aeronet_sdav3.py
  pyaerocom/io/read_aeronet_sunv3.py
  pyaerocom/io/read_earlinet.py
  pyaerocom/io/read_ebas.py
  pyaerocom/io/read_eea_aqerep_base.py
  pyaerocom/io/readaeronetbase.py
  pyaerocom/io/readgridded.py
  pyaerocom/io/readungriddedbase.py
  pyaerocom/vert_coords.py
Labels: code-health 🏥
