Repository metno/pyaerocom, pull requests merged in 2025-05, with the labels that each got.

#1609 Refactor setup_class.py into its own directory with modules for each class
  pyaerocom/aeroval/__init__.py
  pyaerocom/aeroval/setup/__init__.py
  pyaerocom/aeroval/setup/cams2_83_setup.py
  pyaerocom/aeroval/setup/eval_run_options.py
  pyaerocom/aeroval/setup/eval_setup.py
  pyaerocom/aeroval/setup/experiment_info.py
  pyaerocom/aeroval/setup/model_maps_setup.py
  pyaerocom/aeroval/setup/output_paths.py
  pyaerocom/aeroval/setup/project_info.py
  pyaerocom/aeroval/setup/statistics_setup.py
  pyaerocom/aeroval/setup/time_setup.py
  pyaerocom/aeroval/setup/web_display_setup.py
  tests/aeroval/setup/__init__.py
  tests/aeroval/setup/test_eval_setup.py
  tests/aeroval/test_experiment_output.py
Labels: code-health 🏥

#1575 [Units] - Part 3
  docs/api.rst
  pyaerocom/_lowlevel_helpers.py
  pyaerocom/aeroval/_processing_base.py
  pyaerocom/aeroval/coldatatojson_engine.py
  pyaerocom/aeroval/experiment_output.py
  pyaerocom/aeroval/modelmaps_engine.py
  pyaerocom/colocation/colocation_3d.py
  pyaerocom/colocation/colocation_utils.py
  pyaerocom/colocation/colocator.py
  pyaerocom/griddeddata.py
  pyaerocom/io/aux_read_cubes.py
  pyaerocom/io/ghost/additional_variables.py
  pyaerocom/io/iris_io.py
  pyaerocom/io/mscw_ctm/reader.py
  pyaerocom/io/read_aasetal.py
  pyaerocom/io/read_earlinet.py
  pyaerocom/io/read_eea_aqerep_base.py
  pyaerocom/io/readungridded.py
  pyaerocom/stationdata.py
  pyaerocom/ungridded_data_container.py
  pyaerocom/ungridded_data_metadata.py
  pyaerocom/ungriddeddata.py
  pyaerocom/ungriddeddata_structured.py
  pyaerocom/units/helpers.py
  pyaerocom/units/logging/__init__.py
  pyaerocom/units/logging/callbacks.py
  pyaerocom/units/typing/__init__.py
  pyaerocom/units/typing/protocols.py
  pyaerocom/units/units.py
  pyaerocom/units/units_helpers.py
  pyaerocom/utils.py
  pyaerocom_env.yml
  pyproject.toml
  test.py
  tests/aeroval/test_modelmaps_engine.py
  tests/fixtures/pyaro.py
  tests/fixtures/stations.py
  tests/io/mscw_ctm/test_reader.py
  tests/test_griddeddata.py
  tests/test_stationdata.py
  tests/test_ungriddeddata_structured.py
  tests/units/logging/test_callbacks.py
  tests/units/test_units.py
Labels: code-health 🏥, aerotools convo 💬

#1621 Remove eprofile get list test
  tests/io/test_read_eprofile.py
Labels: testing

#1625 Add all the needed output to the fairmode files
  pyaerocom/aeroval/fairmode_statistics.py
  pyaerocom/scripts/cams2_83/engine.py
  tests/aeroval/test_coldatatojson_helpers2.py
  tests/aeroval/test_fairmode_statistics.py
  tests/cams2_83/test_cams2_83_engine.py
Labels: CAMS2_83

#1403 add aeroval configurations to be run on CI
  pyaerocom/aeroval/config/ciconfigs/__init__.py
  pyaerocom/aeroval/config/ciconfigs/base_config.py
  pyaerocom/config.py
  pyaerocom/data/paths.ini
  pyaerocom/io/aerocom_browser.py
  pyaerocom/sample_data_access/minimal_dataset.py
  pyaerocom_env.yml
  pyproject.toml
  tests/aeroval/test_aeroval_config_diurnal.py
  tests/conftest.py
  tests/fixtures/emep_ci.py
  tests/test_metastandards.py
Labels: missing-tests

#1636 Improve regions bound checking performance
  pyaerocom/aeroval/coldatatojson_helpers.py
  pyaerocom/helpers_landsea_masks.py
  pyaerocom/region.py
  pyaerocom/trends_helpers.py
  test-regions.prof
Labels: performance 🏎️

#1638 EPROFILE: New format
  pyaerocom/io/read_eprofile.py
  pyaerocom/sample_data_access/minimal_dataset.py
  pyaerocom_env.yml
  pyproject.toml
  tests/aeroval/test_aeroval_config_diurnal.py
  tests/io/test_read_eprofile.py
Labels: obs-update, CAMS2_82

#1640 Use pypi release of pyaro-readers
  pyaerocom_env.yml
  pyproject.toml
Labels: dependencies
