Repository metno/pyaerocom, pull requests merged in 2025-02, with the labels that each got.

#1496 Remove obsolete l2satellite stuff
  pyaerocom/extras/__init__.py
  pyaerocom/extras/satellite_l2/__init__.py
  pyaerocom/extras/satellite_l2/aeolus_l2a.py
  pyaerocom/extras/satellite_l2/base_reader.py
  pyaerocom/extras/satellite_l2/sentinel5p.py
Labels: code-health 🏥

#1458 Bulkfraction engine for pyaeroval
  pyaerocom/aeroval/bulkfraction_engine.py
  pyaerocom/aeroval/data/var_scale_colmap.ini
  pyaerocom/aeroval/data/var_web_info.ini
  pyaerocom/aeroval/experiment_processor.py
  pyaerocom/aeroval/obsentry.py
  pyaerocom/aux_var_helpers.py
  pyaerocom/colocation/colocator.py
  pyaerocom/data/ebas_config.ini
  pyaerocom/data/variables.ini
  pyaerocom/io/mscw_ctm/emep_variables.toml
  pyaerocom/io/mscw_ctm/reader.py
  pyaerocom/io/read_ebas.py
  tests/aeroval/test_bulkfraction_engine.py
  tests/fixtures/aeroval/cfg_test_bulk.py
  tests/io/test_read_ebas.py
  tests/test_varcollection.py
Labels: enhancement ✨

#1492 Optimize computation of timeseries statistics through multiprocessing
  pyaerocom/aeroval/coldatatojson_engine.py
  pyaerocom/aeroval/coldatatojson_helpers.py
  pyaerocom/config.py
Labels: performance 🏎️

#1440 Fix code snippets in documentation for doctest
  conftest.py
  pyaerocom/_lowlevel_helpers.py
  pyaerocom/aeroval/config/emep/emep4no_base_config.py
  pyaerocom/griddeddata.py
  pyaerocom/io/file_conventions.py
  pyaerocom/io/read_aeronet_invv3.py
  pyaerocom/io/readungridded.py
  pyaerocom/io/utils.py
  pyaerocom/mathutils.py
  pyaerocom/plot/config.py
  pyaerocom/plot/helpers.py
  pyaerocom/ungriddeddata.py
  pyaerocom/utils.py
  pyproject.toml
  tests/fixtures/cams2_83/__init__.py
Labels: testing, documentation 📖

#1521 fairmode calculated only for meaningful var/freq combinations
  pyaerocom/aeroval/coldatatojson_helpers.py
  pyaerocom/aeroval/fairmode_stats.py
  tests/aeroval/test_fairmode_stats.py
Labels: CAMS2_83

#1508 Colocate UEMEP station data
  docs/api.rst
  pyaerocom/aeroval/coldatatojson_engine.py
  pyaerocom/colocation/colocated_data.py
  pyaerocom/colocation/colocation_utils.py
  pyaerocom/colocation/colocator.py
  pyaerocom/colocation/uemep/__init__.py
  pyaerocom/colocation/uemep/colocator.py
  pyaerocom/griddeddata.py
  pyaerocom/io/uemep/__init__.py
  pyaerocom/io/uemep/model_variables.py
  pyaerocom/io/uemep/uemep_variables.ini
  pyaerocom/io/uemep/uemep_variables.toml
  pyaerocom/stationdata.py
  pyaerocom/ungriddeddata.py
  pyaerocom/units_helpers.py
  scripts/uemep.py
  tests/colocation/__init__.py
  tests/colocation/test_colocated_data.py
  tests/colocation/uemep/__init__.py
  tests/colocation/uemep/test_colocator.py
Labels: enhancement ✨

#1356 First draft of new climatology config
  pyaerocom/aeroval/_processing_base.py
  pyaerocom/aeroval/obsentry.py
  pyaerocom/climatology_config.py
  pyaerocom/colocation/colocation_3d.py
  pyaerocom/colocation/colocation_setup.py
  pyaerocom/colocation/colocation_utils.py
  pyaerocom/config.py
  pyaerocom/stationdata.py
  tests/colocation/test_colocation_3d.py
  tests/colocation/test_colocation_utils.py
  tests/colocation/test_colocator.py
  tests/test_config.py
  tests/test_stationdata.py
Labels: bug :bug:, enhancement ✨

#1524 Fixes for move of overlay out of contour
  pyaerocom/aeroval/experiment_output.py
  pyaerocom/aeroval/modelmaps_engine.py
  pyaerocom/aeroval/setup_classes.py
Labels: bug :bug:
