Repository metno/pyaerocom, pull requests merged in 2025-03, with the labels that each got.

#1535 disable caching for pyaro based datasets
  pyaerocom/io/readungridded.py
Labels: obs-update

#1546 Math typesetting in variable menu names
  pyaerocom/aeroval/data/var_web_info.ini
Labels: enhancement ✨

#1529 Implement areovaldb querying for accessing file metadata in pyaerocom
  pyaerocom/aeroval/coldatatojson_engine.py
  pyaerocom/aeroval/experiment_output.py
  pyaerocom/aeroval/modelmaps_engine.py
  pyaerocom/scripts/cams2_83/engine.py
  pyaerocom_env.yml
  pyproject.toml
  tests/aeroval/test_aeroval_HIGHLEV.py
  tests/aeroval/test_bulkfraction_engine.py
  tests/aeroval/test_experiment_output.py
  tests/aeroval/test_modelmaps_engine.py
  tests/cams2_83/test_cams2_83_cli_mos.py
Labels: enhancement ✨

#1557 Add solar irradiation variables
  pyaerocom/data/variables.ini
Labels: new-obs, CAMS2_73

#1558 ci: Parallellize conda
  .github/workflows/CI.yml
  pyaerocom_env.yml
Labels: testing

#1559 Colocated data from Mines Paris + solar irradiance variables
  pyaerocom/aeroval/coldatatojson_engine.py
  pyaerocom/aeroval/data/var_scale_colmap.ini
  pyaerocom/aeroval/data/var_web_info.ini
  pyaerocom/aeroval/glob_defaults.py
Labels: new-obs
