Repository metno/pyaerocom, pull requests merged in 2025-07, with the labels that each got.

#1672 Diurnal fix
  pyaerocom/aeroval/coldatatojson_engine.py
Labels: bug :bug:

#1665 Small units bug
  pyaerocom/io/read_ebas.py
  pyaerocom/units/datetime/time_config.py
  pyaerocom/units/molecular_mass.py
  pyaerocom/units/units.py
  tests/io/test_read_ebas.py
  tests/units/test_units.py
Labels: bug :bug:

#1681 Create GitHub Workflow to clear cache in CI
  .github/workflows/clear_ci_cache
Labels: testing, automation 🤖

#1683 Update clear_ci_cache.yml
  .github/workflows/clear_ci_cache.yml
Labels: testing, automation 🤖

#1686 Tidy up PR 1656
  pyaerocom/aeroval/coldatatojson_engine.py
  pyaerocom/colocation/colocation_3d.py
  pyaerocom/colocation/colocation_setup.py
  pyaerocom/ungriddeddata_structured.py
Labels: style

#1671 Add units wherever data is provided
  pyaerocom/aeroval/coldatatojson_helpers.py
  pyaerocom/colocation/colocated_data.py
  pyaerocom/data/variables.ini
Labels: new-feature, SESAM

#1687 SESAM: Glyoxal, CO + Logging Enhancements
  pyaerocom/aeroval/data/var_scale_colmap.ini
  pyaerocom/aeroval/data/var_web_info.ini
  pyaerocom/aeroval/experiment_output.py
  pyaerocom/aeroval/experiment_processor.py
  pyaerocom/colocation/colocator.py
  pyaerocom/data/variables.ini
  pyaerocom/griddeddata.py
  pyaerocom/io/readungridded.py
  pyaerocom/scripts/cli.py
  tests/aeroval/test_experiment_output.py
Labels: user-friendliness, SESAM

#1692 Const refactor
  pyaerocom/__init__.py
  pyaerocom/aeroval/coldatatojson_helpers.py
  pyaerocom/colocation/colocation_setup.py
  pyaerocom/config_reader.py
  pyaerocom/filter.py
  pyaerocom/io/helpers.py
  pyaerocom/io/readungridded.py
  pyaerocom/io/readungriddedbase.py
  pyaerocom/region.py
  pyaerocom_env.yml
  pyproject.toml
  tests/colocation/test_colocated_data.py
  tests/colocation/test_colocation_setup.py
  tests/colocation/test_colocation_utils.py
  tests/colocation/test_colocator.py
  tests/fixtures/aeroval/cams84.py
  tests/fixtures/aeroval/cfg_test_exp1.py
  tests/fixtures/aeroval/cfg_test_exp2.py
  tests/fixtures/aeroval/cfg_test_exp3.py
  tests/fixtures/aeroval/cfg_test_exp4.py
  tests/fixtures/aeroval/cfg_test_exp5.py
  tests/fixtures/collocated_data.py
  tests/fixtures/tm5.py
  tests/test_config_reader.py
  tests/test_filter.py
Labels: testing, code-health 🏥

#1696 Lowlevel helpers weeding
  pyaerocom/_lowlevel_helpers.py
  pyaerocom/aeroval/_processing_base.py
  pyaerocom/aeroval/experiment_output.py
  tests/aeroval/test_experiment_output.py
  tests/test__lowlevel_helpers.py
Labels: code-health 🏥
