Repository metno/pyaerocom, pull requests merged in 2025-01, with the labels that each got.

#1466 Warn user if var_order_menu does not match used variables
  pyaerocom/aeroval/setup_classes.py
Labels: nice-thing-to-have-🍨

#1444 Fix modelmaps
  pyaerocom/aeroval/modelmaps_engine.py
  pyaerocom/io/cams2_83/reader.py
  tests/aeroval/test_modelmaps_engine.py
Labels: bug :bug:

#1475 remove tox dependencies
  pyproject.toml
Labels: dependencies

#1478 Fix typo
  pyaerocom/aeroval/config/emep/reporting_base.py
Labels: bug :bug:

#1483 Revert "remove tox dependencies"
  pyproject.toml
Labels: testing

#1482 Removes some file path references in exp output which are no longer needed.
  pyaerocom/aeroval/experiment_output.py
  tests/aeroval/test_aeroval_HIGHLEV.py
  tests/aeroval/test_experiment_output.py
Labels: code-health 🏥

#1485 Update pyproject.toml for aerovaldb 0.2.3
  pyproject.toml
Labels: dependencies

#1489 Renaming of proxy vars for contours and overlays
  pyaerocom/aeroval/modelmaps_engine.py
Labels: CAMS2_82

#1491 Add pyaerocom logo to README.rst and readthedocs
  README.rst
  docs/aerotools_workflow_202407.png
  docs/aerotools_workflow_202501.png
  docs/conf.py
  docs/index.rst
  docs/pyaerocom_logo.png
Labels: nice-thing-to-have-🍨

#1494 Pin contourpy >=1.3.0
  pyaerocom_env.yml
  pyproject.toml
Labels: dependencies
