Repository metno/pyaerocom, pull requests merged in 2025-06, with the labels that each got.

#1635 Adds NOTE to colocate_time about model interpolation
  pyaerocom/colocation/colocation_setup.py
  pyaerocom/colocation/colocation_utils.py
Labels: documentation 📖

#1648 run forecast against set of observations meant for analysis
  pyaerocom/io/cams2_83/read_obs.py
  pyaerocom/scripts/cams2_83/cli.py
  tests/cams2_83/test_cams2_83_cli.py
Labels: new-feature, CAMS2_83

#1653 Mitigate test warnings
  conftest.py
  pyaerocom/_lowlevel_helpers.py
  pyaerocom/io/icpforests/reader.py
  pyproject.toml
Labels: code-health 🏥

#1657 process colocated files for conco3mda8 in a cams2_83 mos experiment
  pyaerocom/aeroval/experiment_processor.py
  pyaerocom/scripts/cams2_83/cli_mos.py
  pyaerocom/scripts/cams2_83/engine.py
  pyaerocom/scripts/cams2_83/evaluation.py
Labels: CAMS2_83

#1662 Make sorting of values and errors consistent (+ resample errors)
  pyaerocom/helpers.py
  pyaerocom/stationdata.py
  pyaerocom/ungriddeddata.py
  pyaerocom/ungriddeddata_structured.py
  tests/fixtures/stations.py
  tests/test_helpers.py
Labels: bug :bug:

#1659 Cams283 exceedance ind
  pyaerocom/aeroval/fairmode_statistics.py
  tests/aeroval/test_fairmode_statistics.py
Labels: CAMS2_83
